import 'package:flutter/material.dart';

/// A short prose summary of a class's analytics, generated by calling the
/// `summarise-class` edge function with figures already computed elsewhere
/// on screen.
///
/// This widget never computes the summary itself and never asserts on its
/// wording: [generate] is injected so a test can supply a fake, and a real
/// caller would hand it something that POSTs to `summarise-class`. Caching
/// is deliberately kept out-of-process here -- [cachedSummary] is whatever
/// the caller last persisted (e.g. from `generated_content`), so this widget
/// stays presentational and testable without a live database, matching the
/// Task 4/5 panels in this directory. Wiring a real `generated_content`
/// cache is left to whichever screen composes this panel.
///
/// Requirement 54: a failed generate call must never take the surrounding
/// dashboard down with it -- the chart panels next to this one keep working
/// regardless, and this widget itself degrades to the cached summary, or to
/// a plain "summary unavailable" notice if there is no cache either.
class AiSummaryPanel extends StatefulWidget {
  const AiSummaryPanel({
    super.key,
    required this.generate,
    this.cachedSummary,
  });

  /// Calls the `summarise-class` function (or a fake, in tests) and returns
  /// the generated prose. May throw -- a network failure, a 4xx/5xx, or a
  /// Gemini failure all surface as an exception here.
  final Future<String> Function() generate;

  /// The last summary persisted for this class, shown immediately and used
  /// as the fallback if [generate] fails or the device is offline.
  final String? cachedSummary;

  @override
  State<AiSummaryPanel> createState() => _AiSummaryPanelState();
}

class _AiSummaryPanelState extends State<AiSummaryPanel> {
  String? _summary;
  bool _loading = true;
  bool _failed = false;

  @override
  void initState() {
    super.initState();
    _summary = widget.cachedSummary;
    _refresh();
  }

  Future<void> _refresh() async {
    try {
      final String result = await widget.generate();
      if (!mounted) return;
      setState(() {
        _summary = result;
        _loading = false;
        _failed = false;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _loading = false;
        _failed = true;
        // _summary is left as whatever cachedSummary was: the fallback.
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final String? summary = _summary;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Row(
              children: <Widget>[
                const Icon(Icons.auto_awesome, size: 16),
                const SizedBox(width: 6),
                Text(
                  'AI-generated summary',
                  key: const Key('ai-summary-label'),
                  style: Theme.of(context).textTheme.labelMedium,
                ),
              ],
            ),
            const SizedBox(height: 8),
            if (_loading && summary == null)
              const Text(
                'Generating a summary...',
                key: Key('ai-summary-loading'),
              )
            else if (summary != null)
              Text(summary, key: const Key('ai-summary-text'))
            else if (_failed)
              const Text(
                'Summary unavailable. The chart above is still up to date.',
                key: Key('ai-summary-unavailable'),
              ),
            if (_failed && summary != null)
              const Padding(
                padding: EdgeInsets.only(top: 4),
                child: Text(
                  'Showing the last saved summary -- could not refresh it just now.',
                  key: Key('ai-summary-stale-notice'),
                  style: TextStyle(fontSize: 12),
                ),
              ),
          ],
        ),
      ),
    );
  }
}
